sudo: false
language: bash
addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - bats
      - bc
      - lockfile-progs
      - procmail
      - sra-toolkit
      - mash/bionic
      - sqlite3
before_install:
  - cd ~
  - /bin/bash
  - perl -MNet::FTP -e '$ftp = new Net::FTP("ftp.ncbi.nlm.nih.gov", Passive => 1); $ftp->login; $ftp->binary; $ftp->get("/entrez/entrezdirect/edirect.tar.gz");' 
  - gunzip -c edirect.tar.gz | tar xf -
  - rm edirect.tar.gz
  - builtin exit
  - export PATH=$PATH:$HOME/edirect >& /dev/null || setenv PATH "${PATH}:$HOME/edirect"
  - ./edirect/setup.sh
script: bats --tap t/*.sh

