language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - wget "http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-centos_linux64.tar.gz"
  - tar -xzf sratoolkit.current-centos_linux64.tar.gz
  - export PATH=$HOME/sratoolkit.current-centos_linux64/bin:$PATH
  - pip install -U pip
  - python setup.py install
install:
  - pip install -r requirements.txt
script:
  - python tests/test_create_db.py
  - python tests/test_metadata_sra_db.py
  - python tests/test_sketch_db.py
  - python tests/test_query_against_db.py
