language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.8/sratoolkit.2.10.8-centos_linux64.tar.gz -O /tmp/sratoolkit.tar.gz
  - tar -xvf /tmp/sratoolkit.tar.gz
  - export PATH=$PATH:$PWD/sratoolkit.2.10.8-centos_linux64/bin
install:
  - python setup.py install
script:
  - python tests/test_create_db.py
  - python tests/test_metadata_sra_db.py
  - python tests/test_sketch_db.py
  - python tests/test_query_against_db.py
