language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - pip install -U pip
  - python setup.py install
install:
  - pip install biopython
  - pip install pandas
  - pip install sourmash
script:
  - python tests/test_create_db.py
