sudo: false
language: bash
addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - bats
      - bc
      - lockfile-progs
      - procmail
      - sra-toolkit
      - sqlite3
before_install:
  - export PATH=$PATH:$HOME/mashpit/edirect >& /dev/null || setenv PATH "${PATH}:$HOME/edirect"
  - yes | ./edirect/setup.sh
  - wget https://github.com/marbl/Mash/releases/download/v2.2/mash-Linux64-v2.2.tar
  - tar xvf mash-Linux64-v2.2.tar
  - export PATH=$PATH:$(pwd)/mash-Linux64-v2.2
  - chmod -v +x $(pwd)/mash-Linux64-v2.2/mash
script: bats --tap t/*.sh

